---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.mysql
    - role: ome.mysql_backup
      mysql_backup_dir: /var/backups/database
      mysql_backup_filename_format: "bdditescia-%Y%m%d.mysqldump"
      mysql_backup_minimum_expected_size: 100000

