#---
#- name: Install packages
#    package:
#    name: htop
#    state: present
#- name: Install packages 2 
#    package:
#    name: 
#    state: present
---
- name: Install packages
  apt:
         name: "{{item}}"
  loop: "{{packages}}"
